# Generated by Django 4.2 on 2023-05-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0011_remove_nodes_post'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('IdData', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.BigIntegerField()),
                ('humidity', models.BigIntegerField()),
                ('wind', models.BigIntegerField(default=0)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='compte.nodes')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
