# Generated by Django 4.2 on 2023-05-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_data_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='wind',
        ),
    ]
