# Generated by Django 4.2 on 2023-05-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_data_wind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='node',
            new_name='nodes',
        ),
    ]
