# Generated by Django 4.2 on 2023-05-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superviseur', '0001_initial'),
        ('client', '0004_rename_node_data_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='nodes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='superviseur.nodes'),
        ),
    ]
