# Generated by Django 4.2 on 2023-05-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0013_nodes_alter_client_node'),
        ('client', '0005_alter_data_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='nodes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='compte.nodes'),
        ),
    ]
