# Generated by Django 4.2 on 2023-05-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_data_nodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
