# Generated by Django 4.2 on 2023-05-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_data_nodes'),
        ('compte', '0013_nodes_alter_client_node'),
        ('superviseur', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nodes',
        ),
    ]
