# Generated by Django 4.2 on 2023-05-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superviseur', '0004_alter_nodes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
