# Generated by Django 4.2 on 2023-05-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_delete_data'),
        ('superviseur', '0005_alter_nodes_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nodes',
        ),
    ]
