# Generated by Django 4.1.7 on 2023-04-19 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superviseur',
            name='image',
        ),
    ]
