# Generated by Django 4.1.7 on 2023-04-19 05:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_remove_superviseur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='superviseur',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='superviseur',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
