# Generated by Django 4.2 on 2023-04-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_superviseur_image_superviseur_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.RemoveField(
            model_name='superviseur',
            name='image',
        ),
        migrations.RemoveField(
            model_name='superviseur',
            name='position',
        ),
    ]
