# Generated by Django 4.2 on 2023-04-29 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0005_rename_pseudo_client_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='superviseur',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='compte.superviseur'),
            preserve_default=False,
        ),
    ]
