# Generated by Django 4.2 on 2023-05-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0007_client_client_id_superviseur_superviseur_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
    ]
