# Generated by Django 4.2 on 2023-05-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('compte', '0009_nodes_remove_client_position_client_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='Post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='client.post'),
        ),
    ]
