# Generated by Django 4.2 on 2023-05-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_data_nodes'),
        ('superviseur', '0001_initial'),
        ('compte', '0011_remove_nodes_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='superviseur.nodes'),
        ),
        migrations.DeleteModel(
            name='nodes',
        ),
    ]
