# Generated by Django 4.2 on 2023-05-11 16:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0012_alter_client_node_delete_nodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='nodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='compte.nodes'),
        ),
    ]
