# Generated by Django 4.2 on 2023-05-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0013_nodes_alter_client_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='node',
        ),
        migrations.AddField(
            model_name='nodes',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='compte.client'),
        ),
    ]
