# Generated by Django 4.2 on 2023-05-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0014_remove_client_node_nodes_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='client',
        ),
    ]
