# Generated by Django 4.2 on 2023-05-11 16:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0017_alter_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='nodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Position', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='compte.client')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('IdData', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.BigIntegerField()),
                ('humidity', models.BigIntegerField()),
                ('nodes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='compte.nodes')),
            ],
        ),
    ]
