# Generated by Django 4.2 on 2023-05-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0020_alter_client_id_alter_superviseur_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='superviseur',
        ),
        migrations.RemoveField(
            model_name='data',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='nodes',
            name='client',
        ),
    ]
