# Generated by Django 4.2 on 2023-05-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0021_remove_client_superviseur_remove_data_nodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='superviseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='compte.superviseur'),
        ),
        migrations.AddField(
            model_name='data',
            name='nodes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='compte.nodes'),
        ),
        migrations.AddField(
            model_name='nodes',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='compte.client'),
        ),
    ]
